## Feature engineering

L'idée maintenant est d'ajouter aux features déjà existantes de nouvelles features. Par exemple:
 - comment encoder la date ? 
 - comment encoder la météo ? 
 - quelles autres features peuvent avoir de l'importance pour notre prédiction ? 
 - faut-il notre target pour la rendre "regression-friendly" ?

In [ ]:
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [ ]:
data = pd.read_parquet(Path.cwd().parent / "data/raw/bikes.parquet")

,counter_id,counter_name,site_id,site_name,bike_count,date,counter_installation_date,coordinates,counter_technical_id,latitude,longitude,log_bike_count
48321,100007049-102007049,28 boulevard Diderot E-O,100007049,28 boulevard Diderot,0.0,2020-09-01 02:00:00,2013-01-18,"48.846028,2.375429",Y2H15027244,48.846028,2.375429,0.000000
48324,100007049-102007049,28 boulevard Diderot E-O,100007049,28 boulevard Diderot,1.0,2020-09-01 03:00:00,2013-01-18,"48.846028,2.375429",Y2H15027244,48.846028,2.375429,0.693147
48327,100007049-102007049,28 boulevard Diderot E-O,100007049,28 boulevard Diderot,0.0,2020-09-01 04:00:00,2013-01-18,"48.846028,2.375429",Y2H15027244,48.846028,2.375429,0.000000
48330,100007049-102007049,28 boulevard Diderot E-O,100007049,28 boulevard Diderot,4.0,2020-09-01 15:00:00,2013-01-18,"48.846028,2.375429",Y2H15027244,48.846028,2.375429,1.609438
48333,100007049-102007049,28 boulevard Diderot E-O,100007049,28 boulevard Diderot,9.0,2020-09-01 18:00:00,2013-01-18,"48.846028,2.375429",Y2H15027244,48.846028,2.375429,2.302585

Informations sur quelques colonnes

In [ ]:
data = data.sort_values(["date", "counter_name"])

## Feature extraction

Pour prendre en compte les aspects temporels de notre dataset, il nous faut extraire certaines features liés à la temporalité.

In [ ]:
def _encode_dates(X):
    X = X.copy()

    X["year"] = X["date"].dt.year
    X["month"] = X["date"].dt.month
    X["day"] = X["date"].dt.day
    X["weekday"] = X["date"].dt.weekday
    X["hour"] = X["date"].dt.hour

    return X.drop(columns=["date"])

In [ ]:
data["date"].head()

48321   2020-09-01 02:00:00
48324   2020-09-01 03:00:00
48327   2020-09-01 04:00:00
48330   2020-09-01 15:00:00
48333   2020-09-01 18:00:00
Name: date, dtype: datetime64[us]

In [ ]:
_encode_dates(data[["date"]].head())

       year  month  day  weekday  hour
48321  2020      9    1        1     2
48324  2020      9    1        1     3
48327  2020      9    1        1     4
48330  2020      9    1        1    15
48333  2020      9    1        1    18

Pour pouvoir l'utiliser avec scikit-learn on a besoin de [FunctionTransformer](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.FunctionTransformer.html):

In [ ]:
from sklearn.preprocessing import FunctionTransformer

date_encoder = FunctionTransformer(_encode_dates, validate=False)
sample_encoded = date_encoder.fit_transform(data[["date"]]).head()
sample_encoded

       year  month  day  weekday  hour
48321  2020      9    1        1     2
48324  2020      9    1        1     3
48327  2020      9    1        1     4
48330  2020      9    1        1    15
48333  2020      9    1        1    18

On encode les features catégorielles pour nos modèles linéaires, par exemple avec un [OneHotEncoder](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html).

In [ ]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(sparse_output=False)

enc.fit_transform(sample_encoded[["hour"]])

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])